version: '3.1'

services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    ports:
      - "1521:1521"   # Oracle database default port
      - "8080:8080"   # Oracle Apex default port
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_USERNAME=SYSTEM
      - ORACLE_PASSWORD=password
    volumes:
      - oracle-data:/u01/app/oracle

  demo:
    image: demo:latest
    container_name: demo-service
    depends_on:
      oracle:
        condition: service_started
    build:
      context: . # The directory containing the Dockerfile
      dockerfile: Dockerfile # The name of the Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle:1521/XE
      SPRING_DATASOURCE_USERNAME: SYSTEM
      SPRING_DATASOURCE_PASSWORD: oracle
    volumes:
      - oracle-data:/u01/app/oracle

volumes:
  oracle-data:
    driver: local