INSERT INTO SYSTEM.USERS (ID, NAME, RATING) VALUES (1, 'User One', 100);
INSERT INTO SYSTEM.USERS (ID, NAME, RATING) VALUES (2, 'User Two', 200);
INSERT INTO SYSTEM.USERS (ID, NAME, RATING) VALUES (3, 'User Three', 300);
INSERT INTO SYSTEM.USERS (ID, NAME, RATING) VALUES (4, 'User Four', 400);
INSERT INTO SYSTEM.USERS (ID, NAME, RATING) VALUES (5, 'User Five', 500);
